version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "05:00"
      timezone: "Europe/Stockholm"
    groups:
      actions-patch-minor:
        update-types: ["minor", "patch"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "05:00"
      timezone: "Europe/Stockholm"
    groups:
      npm-patch-minor:
        update-types: ["minor", "patch"]
